// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.25.3
// source: broker/metadata.proto

package broker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClusterMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brokers       map[string]*BrokerInfo `protobuf:"bytes,1,rep,name=brokers,proto3" json:"brokers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Topics        map[string]*TopicInfo  `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastIndex     int64                  `protobuf:"varint,3,opt,name=last_index,json=lastIndex,proto3" json:"last_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMetadata) Reset() {
	*x = ClusterMetadata{}
	mi := &file_broker_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMetadata) ProtoMessage() {}

func (x *ClusterMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_broker_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMetadata.ProtoReflect.Descriptor instead.
func (*ClusterMetadata) Descriptor() ([]byte, []int) {
	return file_broker_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterMetadata) GetBrokers() map[string]*BrokerInfo {
	if x != nil {
		return x.Brokers
	}
	return nil
}

func (x *ClusterMetadata) GetTopics() map[string]*TopicInfo {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *ClusterMetadata) GetLastIndex() int64 {
	if x != nil {
		return x.LastIndex
	}
	return 0
}

type BrokerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Alive         bool                   `protobuf:"varint,3,opt,name=alive,proto3" json:"alive,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerInfo) Reset() {
	*x = BrokerInfo{}
	mi := &file_broker_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerInfo) ProtoMessage() {}

func (x *BrokerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_broker_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerInfo.ProtoReflect.Descriptor instead.
func (*BrokerInfo) Descriptor() ([]byte, []int) {
	return file_broker_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *BrokerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BrokerInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BrokerInfo) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *BrokerInfo) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type TopicInfo struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Name          string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Partitions    map[int32]*PartitionInfo `protobuf:"bytes,2,rep,name=partitions,proto3" json:"partitions,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicInfo) Reset() {
	*x = TopicInfo{}
	mi := &file_broker_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicInfo) ProtoMessage() {}

func (x *TopicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_broker_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicInfo.ProtoReflect.Descriptor instead.
func (*TopicInfo) Descriptor() ([]byte, []int) {
	return file_broker_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *TopicInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopicInfo) GetPartitions() map[int32]*PartitionInfo {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type PartitionInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TopicName      string                 `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	Leader         string                 `protobuf:"bytes,3,opt,name=leader,proto3" json:"leader,omitempty"`
	LeaderAddress  string                 `protobuf:"bytes,4,opt,name=leader_address,json=leaderAddress,proto3" json:"leader_address,omitempty"`
	Replicas       []string               `protobuf:"bytes,5,rep,name=replicas,proto3" json:"replicas,omitempty"`
	Isr            []string               `protobuf:"bytes,6,rep,name=isr,proto3" json:"isr,omitempty"`
	Epoch          int64                  `protobuf:"varint,7,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Offset         int64                  `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	CommitedOffset int64                  `protobuf:"varint,9,opt,name=commited_offset,json=commitedOffset,proto3" json:"commited_offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PartitionInfo) Reset() {
	*x = PartitionInfo{}
	mi := &file_broker_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionInfo) ProtoMessage() {}

func (x *PartitionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_broker_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionInfo.ProtoReflect.Descriptor instead.
func (*PartitionInfo) Descriptor() ([]byte, []int) {
	return file_broker_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *PartitionInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PartitionInfo) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *PartitionInfo) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

func (x *PartitionInfo) GetLeaderAddress() string {
	if x != nil {
		return x.LeaderAddress
	}
	return ""
}

func (x *PartitionInfo) GetReplicas() []string {
	if x != nil {
		return x.Replicas
	}
	return nil
}

func (x *PartitionInfo) GetIsr() []string {
	if x != nil {
		return x.Isr
	}
	return nil
}

func (x *PartitionInfo) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *PartitionInfo) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PartitionInfo) GetCommitedOffset() int64 {
	if x != nil {
		return x.CommitedOffset
	}
	return 0
}

var File_broker_metadata_proto protoreflect.FileDescriptor

const file_broker_metadata_proto_rawDesc = "" +
	"\n" +
	"\x15broker/metadata.proto\x12\x06broker\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcb\x02\n" +
	"\x0fClusterMetadata\x12>\n" +
	"\abrokers\x18\x01 \x03(\v2$.broker.ClusterMetadata.BrokersEntryR\abrokers\x12;\n" +
	"\x06topics\x18\x02 \x03(\v2#.broker.ClusterMetadata.TopicsEntryR\x06topics\x12\x1d\n" +
	"\n" +
	"last_index\x18\x03 \x01(\x03R\tlastIndex\x1aN\n" +
	"\fBrokersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.broker.BrokerInfoR\x05value:\x028\x01\x1aL\n" +
	"\vTopicsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.broker.TopicInfoR\x05value:\x028\x01\"\x85\x01\n" +
	"\n" +
	"BrokerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x14\n" +
	"\x05alive\x18\x03 \x01(\bR\x05alive\x127\n" +
	"\tlast_seen\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\"\xb8\x01\n" +
	"\tTopicInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12A\n" +
	"\n" +
	"partitions\x18\x02 \x03(\v2!.broker.TopicInfo.PartitionsEntryR\n" +
	"partitions\x1aT\n" +
	"\x0fPartitionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.broker.PartitionInfoR\x05value:\x028\x01\"\x82\x02\n" +
	"\rPartitionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x02 \x01(\tR\ttopicName\x12\x16\n" +
	"\x06leader\x18\x03 \x01(\tR\x06leader\x12%\n" +
	"\x0eleader_address\x18\x04 \x01(\tR\rleaderAddress\x12\x1a\n" +
	"\breplicas\x18\x05 \x03(\tR\breplicas\x12\x10\n" +
	"\x03isr\x18\x06 \x03(\tR\x03isr\x12\x14\n" +
	"\x05epoch\x18\a \x01(\x03R\x05epoch\x12\x16\n" +
	"\x06offset\x18\b \x01(\x03R\x06offset\x12'\n" +
	"\x0fcommited_offset\x18\t \x01(\x03R\x0ecommitedOffsetB0Z.github.com/alexandrecolauto/gofka/proto/brokerb\x06proto3"

var (
	file_broker_metadata_proto_rawDescOnce sync.Once
	file_broker_metadata_proto_rawDescData []byte
)

func file_broker_metadata_proto_rawDescGZIP() []byte {
	file_broker_metadata_proto_rawDescOnce.Do(func() {
		file_broker_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_broker_metadata_proto_rawDesc), len(file_broker_metadata_proto_rawDesc)))
	})
	return file_broker_metadata_proto_rawDescData
}

var file_broker_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_broker_metadata_proto_goTypes = []any{
	(*ClusterMetadata)(nil),       // 0: broker.ClusterMetadata
	(*BrokerInfo)(nil),            // 1: broker.BrokerInfo
	(*TopicInfo)(nil),             // 2: broker.TopicInfo
	(*PartitionInfo)(nil),         // 3: broker.PartitionInfo
	nil,                           // 4: broker.ClusterMetadata.BrokersEntry
	nil,                           // 5: broker.ClusterMetadata.TopicsEntry
	nil,                           // 6: broker.TopicInfo.PartitionsEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_broker_metadata_proto_depIdxs = []int32{
	4, // 0: broker.ClusterMetadata.brokers:type_name -> broker.ClusterMetadata.BrokersEntry
	5, // 1: broker.ClusterMetadata.topics:type_name -> broker.ClusterMetadata.TopicsEntry
	7, // 2: broker.BrokerInfo.last_seen:type_name -> google.protobuf.Timestamp
	6, // 3: broker.TopicInfo.partitions:type_name -> broker.TopicInfo.PartitionsEntry
	1, // 4: broker.ClusterMetadata.BrokersEntry.value:type_name -> broker.BrokerInfo
	2, // 5: broker.ClusterMetadata.TopicsEntry.value:type_name -> broker.TopicInfo
	3, // 6: broker.TopicInfo.PartitionsEntry.value:type_name -> broker.PartitionInfo
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_broker_metadata_proto_init() }
func file_broker_metadata_proto_init() {
	if File_broker_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_broker_metadata_proto_rawDesc), len(file_broker_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_broker_metadata_proto_goTypes,
		DependencyIndexes: file_broker_metadata_proto_depIdxs,
		MessageInfos:      file_broker_metadata_proto_msgTypes,
	}.Build()
	File_broker_metadata_proto = out.File
	file_broker_metadata_proto_goTypes = nil
	file_broker_metadata_proto_depIdxs = nil
}
