// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: controller/controller.proto

package controller

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControllerService_HandleFetchMetadata_FullMethodName   = "/controller.ControllerService/HandleFetchMetadata"
	ControllerService_HandleRegisterBroker_FullMethodName  = "/controller.ControllerService/HandleRegisterBroker"
	ControllerService_HandleCreateTopic_FullMethodName     = "/controller.ControllerService/HandleCreateTopic"
	ControllerService_HandleBrokerHeartbeat_FullMethodName = "/controller.ControllerService/HandleBrokerHeartbeat"
)

// ControllerServiceClient is the client API for ControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControllerServiceClient interface {
	HandleFetchMetadata(ctx context.Context, in *BrokerMetadataRequest, opts ...grpc.CallOption) (*BrokerMetadataResponse, error)
	HandleRegisterBroker(ctx context.Context, in *BrokerRegisterRequest, opts ...grpc.CallOption) (*BrokerRegisterResponse, error)
	HandleCreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*CreateTopicResponse, error)
	HandleBrokerHeartbeat(ctx context.Context, in *BrokerHeartbeatRequest, opts ...grpc.CallOption) (*BrokerHeartbeatResponse, error)
}

type controllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerServiceClient(cc grpc.ClientConnInterface) ControllerServiceClient {
	return &controllerServiceClient{cc}
}

func (c *controllerServiceClient) HandleFetchMetadata(ctx context.Context, in *BrokerMetadataRequest, opts ...grpc.CallOption) (*BrokerMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrokerMetadataResponse)
	err := c.cc.Invoke(ctx, ControllerService_HandleFetchMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) HandleRegisterBroker(ctx context.Context, in *BrokerRegisterRequest, opts ...grpc.CallOption) (*BrokerRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrokerRegisterResponse)
	err := c.cc.Invoke(ctx, ControllerService_HandleRegisterBroker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) HandleCreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*CreateTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTopicResponse)
	err := c.cc.Invoke(ctx, ControllerService_HandleCreateTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) HandleBrokerHeartbeat(ctx context.Context, in *BrokerHeartbeatRequest, opts ...grpc.CallOption) (*BrokerHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrokerHeartbeatResponse)
	err := c.cc.Invoke(ctx, ControllerService_HandleBrokerHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServiceServer is the server API for ControllerService service.
// All implementations must embed UnimplementedControllerServiceServer
// for forward compatibility.
type ControllerServiceServer interface {
	HandleFetchMetadata(context.Context, *BrokerMetadataRequest) (*BrokerMetadataResponse, error)
	HandleRegisterBroker(context.Context, *BrokerRegisterRequest) (*BrokerRegisterResponse, error)
	HandleCreateTopic(context.Context, *CreateTopicRequest) (*CreateTopicResponse, error)
	HandleBrokerHeartbeat(context.Context, *BrokerHeartbeatRequest) (*BrokerHeartbeatResponse, error)
	mustEmbedUnimplementedControllerServiceServer()
}

// UnimplementedControllerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControllerServiceServer struct{}

func (UnimplementedControllerServiceServer) HandleFetchMetadata(context.Context, *BrokerMetadataRequest) (*BrokerMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleFetchMetadata not implemented")
}
func (UnimplementedControllerServiceServer) HandleRegisterBroker(context.Context, *BrokerRegisterRequest) (*BrokerRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleRegisterBroker not implemented")
}
func (UnimplementedControllerServiceServer) HandleCreateTopic(context.Context, *CreateTopicRequest) (*CreateTopicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleCreateTopic not implemented")
}
func (UnimplementedControllerServiceServer) HandleBrokerHeartbeat(context.Context, *BrokerHeartbeatRequest) (*BrokerHeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleBrokerHeartbeat not implemented")
}
func (UnimplementedControllerServiceServer) mustEmbedUnimplementedControllerServiceServer() {}
func (UnimplementedControllerServiceServer) testEmbeddedByValue()                           {}

// UnsafeControllerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServiceServer will
// result in compilation errors.
type UnsafeControllerServiceServer interface {
	mustEmbedUnimplementedControllerServiceServer()
}

func RegisterControllerServiceServer(s grpc.ServiceRegistrar, srv ControllerServiceServer) {
	// If the following call pancis, it indicates UnimplementedControllerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControllerService_ServiceDesc, srv)
}

func _ControllerService_HandleFetchMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrokerMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).HandleFetchMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_HandleFetchMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).HandleFetchMetadata(ctx, req.(*BrokerMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_HandleRegisterBroker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrokerRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).HandleRegisterBroker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_HandleRegisterBroker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).HandleRegisterBroker(ctx, req.(*BrokerRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_HandleCreateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).HandleCreateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_HandleCreateTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).HandleCreateTopic(ctx, req.(*CreateTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_HandleBrokerHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrokerHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).HandleBrokerHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_HandleBrokerHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).HandleBrokerHeartbeat(ctx, req.(*BrokerHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControllerService_ServiceDesc is the grpc.ServiceDesc for ControllerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControllerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "controller.ControllerService",
	HandlerType: (*ControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleFetchMetadata",
			Handler:    _ControllerService_HandleFetchMetadata_Handler,
		},
		{
			MethodName: "HandleRegisterBroker",
			Handler:    _ControllerService_HandleRegisterBroker_Handler,
		},
		{
			MethodName: "HandleCreateTopic",
			Handler:    _ControllerService_HandleCreateTopic_Handler,
		},
		{
			MethodName: "HandleBrokerHeartbeat",
			Handler:    _ControllerService_HandleBrokerHeartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller/controller.proto",
}
