// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: broker/broker.proto

package broker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IntraBrokerService_FetchRecords_FullMethodName        = "/broker.IntraBrokerService/FetchRecords"
	IntraBrokerService_UpdateFollowerState_FullMethodName = "/broker.IntraBrokerService/UpdateFollowerState"
)

// IntraBrokerServiceClient is the client API for IntraBrokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntraBrokerServiceClient interface {
	FetchRecords(ctx context.Context, in *FetchRecordsRequest, opts ...grpc.CallOption) (*FetchRecordsResponse, error)
	UpdateFollowerState(ctx context.Context, in *UpdateFollowerStateRequest, opts ...grpc.CallOption) (*UpdateFollowerStateResponse, error)
}

type intraBrokerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntraBrokerServiceClient(cc grpc.ClientConnInterface) IntraBrokerServiceClient {
	return &intraBrokerServiceClient{cc}
}

func (c *intraBrokerServiceClient) FetchRecords(ctx context.Context, in *FetchRecordsRequest, opts ...grpc.CallOption) (*FetchRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchRecordsResponse)
	err := c.cc.Invoke(ctx, IntraBrokerService_FetchRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intraBrokerServiceClient) UpdateFollowerState(ctx context.Context, in *UpdateFollowerStateRequest, opts ...grpc.CallOption) (*UpdateFollowerStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFollowerStateResponse)
	err := c.cc.Invoke(ctx, IntraBrokerService_UpdateFollowerState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntraBrokerServiceServer is the server API for IntraBrokerService service.
// All implementations must embed UnimplementedIntraBrokerServiceServer
// for forward compatibility.
type IntraBrokerServiceServer interface {
	FetchRecords(context.Context, *FetchRecordsRequest) (*FetchRecordsResponse, error)
	UpdateFollowerState(context.Context, *UpdateFollowerStateRequest) (*UpdateFollowerStateResponse, error)
	mustEmbedUnimplementedIntraBrokerServiceServer()
}

// UnimplementedIntraBrokerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIntraBrokerServiceServer struct{}

func (UnimplementedIntraBrokerServiceServer) FetchRecords(context.Context, *FetchRecordsRequest) (*FetchRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchRecords not implemented")
}
func (UnimplementedIntraBrokerServiceServer) UpdateFollowerState(context.Context, *UpdateFollowerStateRequest) (*UpdateFollowerStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFollowerState not implemented")
}
func (UnimplementedIntraBrokerServiceServer) mustEmbedUnimplementedIntraBrokerServiceServer() {}
func (UnimplementedIntraBrokerServiceServer) testEmbeddedByValue()                            {}

// UnsafeIntraBrokerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntraBrokerServiceServer will
// result in compilation errors.
type UnsafeIntraBrokerServiceServer interface {
	mustEmbedUnimplementedIntraBrokerServiceServer()
}

func RegisterIntraBrokerServiceServer(s grpc.ServiceRegistrar, srv IntraBrokerServiceServer) {
	// If the following call pancis, it indicates UnimplementedIntraBrokerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IntraBrokerService_ServiceDesc, srv)
}

func _IntraBrokerService_FetchRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntraBrokerServiceServer).FetchRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntraBrokerService_FetchRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntraBrokerServiceServer).FetchRecords(ctx, req.(*FetchRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntraBrokerService_UpdateFollowerState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFollowerStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntraBrokerServiceServer).UpdateFollowerState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntraBrokerService_UpdateFollowerState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntraBrokerServiceServer).UpdateFollowerState(ctx, req.(*UpdateFollowerStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IntraBrokerService_ServiceDesc is the grpc.ServiceDesc for IntraBrokerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntraBrokerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "broker.IntraBrokerService",
	HandlerType: (*IntraBrokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchRecords",
			Handler:    _IntraBrokerService_FetchRecords_Handler,
		},
		{
			MethodName: "UpdateFollowerState",
			Handler:    _IntraBrokerService_UpdateFollowerState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "broker/broker.proto",
}
