// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.25.3
// source: visualizer/visualizer.proto

package visualizer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VisualizerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      string                 `protobuf:"bytes,1,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisualizerRequest) Reset() {
	*x = VisualizerRequest{}
	mi := &file_visualizer_visualizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisualizerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisualizerRequest) ProtoMessage() {}

func (x *VisualizerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_visualizer_visualizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisualizerRequest.ProtoReflect.Descriptor instead.
func (*VisualizerRequest) Descriptor() ([]byte, []int) {
	return file_visualizer_visualizer_proto_rawDescGZIP(), []int{0}
}

func (x *VisualizerRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *VisualizerRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *VisualizerRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *VisualizerRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type VisualizerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Commands      []*Command             `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisualizerResponse) Reset() {
	*x = VisualizerResponse{}
	mi := &file_visualizer_visualizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisualizerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisualizerResponse) ProtoMessage() {}

func (x *VisualizerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_visualizer_visualizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisualizerResponse.ProtoReflect.Descriptor instead.
func (*VisualizerResponse) Descriptor() ([]byte, []int) {
	return file_visualizer_visualizer_proto_rawDescGZIP(), []int{1}
}

func (x *VisualizerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VisualizerResponse) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_visualizer_visualizer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_visualizer_visualizer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_visualizer_visualizer_proto_rawDescGZIP(), []int{2}
}

func (x *Command) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Command) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Command) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_visualizer_visualizer_proto protoreflect.FileDescriptor

const file_visualizer_visualizer_proto_rawDesc = "" +
	"\n" +
	"\x1bvisualizer/visualizer.proto\x12\n" +
	"visualizer\"t\n" +
	"\x11VisualizerRequest\x12\x1b\n" +
	"\tnode_type\x18\x01 \x01(\tR\bnodeType\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"_\n" +
	"\x12VisualizerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12/\n" +
	"\bcommands\x18\x02 \x03(\v2\x13.visualizer.CommandR\bcommands\"M\n" +
	"\aCommand\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data2\\\n" +
	"\x11VisualizerService\x12G\n" +
	"\x06Update\x12\x1d.visualizer.VisualizerRequest\x1a\x1e.visualizer.VisualizerResponseB;Z9github.com/alexandrecolauto/gofka/common/proto/visualizerb\x06proto3"

var (
	file_visualizer_visualizer_proto_rawDescOnce sync.Once
	file_visualizer_visualizer_proto_rawDescData []byte
)

func file_visualizer_visualizer_proto_rawDescGZIP() []byte {
	file_visualizer_visualizer_proto_rawDescOnce.Do(func() {
		file_visualizer_visualizer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_visualizer_visualizer_proto_rawDesc), len(file_visualizer_visualizer_proto_rawDesc)))
	})
	return file_visualizer_visualizer_proto_rawDescData
}

var file_visualizer_visualizer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_visualizer_visualizer_proto_goTypes = []any{
	(*VisualizerRequest)(nil),  // 0: visualizer.VisualizerRequest
	(*VisualizerResponse)(nil), // 1: visualizer.VisualizerResponse
	(*Command)(nil),            // 2: visualizer.Command
}
var file_visualizer_visualizer_proto_depIdxs = []int32{
	2, // 0: visualizer.VisualizerResponse.commands:type_name -> visualizer.Command
	0, // 1: visualizer.VisualizerService.Update:input_type -> visualizer.VisualizerRequest
	1, // 2: visualizer.VisualizerService.Update:output_type -> visualizer.VisualizerResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_visualizer_visualizer_proto_init() }
func file_visualizer_visualizer_proto_init() {
	if File_visualizer_visualizer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_visualizer_visualizer_proto_rawDesc), len(file_visualizer_visualizer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_visualizer_visualizer_proto_goTypes,
		DependencyIndexes: file_visualizer_visualizer_proto_depIdxs,
		MessageInfos:      file_visualizer_visualizer_proto_msgTypes,
	}.Build()
	File_visualizer_visualizer_proto = out.File
	file_visualizer_visualizer_proto_goTypes = nil
	file_visualizer_visualizer_proto_depIdxs = nil
}
