// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: visualizer/visualizer.proto

package visualizer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VisualizerService_Update_FullMethodName = "/visualizer.VisualizerService/Update"
)

// VisualizerServiceClient is the client API for VisualizerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VisualizerServiceClient interface {
	Update(ctx context.Context, in *VisualizerRequest, opts ...grpc.CallOption) (*VisualizerResponse, error)
}

type visualizerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVisualizerServiceClient(cc grpc.ClientConnInterface) VisualizerServiceClient {
	return &visualizerServiceClient{cc}
}

func (c *visualizerServiceClient) Update(ctx context.Context, in *VisualizerRequest, opts ...grpc.CallOption) (*VisualizerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VisualizerResponse)
	err := c.cc.Invoke(ctx, VisualizerService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VisualizerServiceServer is the server API for VisualizerService service.
// All implementations must embed UnimplementedVisualizerServiceServer
// for forward compatibility.
type VisualizerServiceServer interface {
	Update(context.Context, *VisualizerRequest) (*VisualizerResponse, error)
	mustEmbedUnimplementedVisualizerServiceServer()
}

// UnimplementedVisualizerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVisualizerServiceServer struct{}

func (UnimplementedVisualizerServiceServer) Update(context.Context, *VisualizerRequest) (*VisualizerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedVisualizerServiceServer) mustEmbedUnimplementedVisualizerServiceServer() {}
func (UnimplementedVisualizerServiceServer) testEmbeddedByValue()                           {}

// UnsafeVisualizerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VisualizerServiceServer will
// result in compilation errors.
type UnsafeVisualizerServiceServer interface {
	mustEmbedUnimplementedVisualizerServiceServer()
}

func RegisterVisualizerServiceServer(s grpc.ServiceRegistrar, srv VisualizerServiceServer) {
	// If the following call pancis, it indicates UnimplementedVisualizerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VisualizerService_ServiceDesc, srv)
}

func _VisualizerService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisualizerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisualizerServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisualizerService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisualizerServiceServer).Update(ctx, req.(*VisualizerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VisualizerService_ServiceDesc is the grpc.ServiceDesc for VisualizerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VisualizerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "visualizer.VisualizerService",
	HandlerType: (*VisualizerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _VisualizerService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "visualizer/visualizer.proto",
}
